#
# Nmake file - Windows version
# Use 'nmake -f Makefile.win'

NODEBUG=1

INCS = /I..\libmseed
OPTS = -D_CRT_SECURE_NO_WARNINGS -DNOFDZIP
LIBS = ..\libmseed\libmseed.lib

BIN = ..\sac2mseed.exe

all: $(BIN)

$(BIN):	sac2mseed.obj
	link.exe /nologo /out:$(BIN) $(LIBS) sac2mseed.obj

.c.obj:
	$(CC) /nologo $(CFLAGS) $(INCS) $(OPTS) /c $<

# Clean-up directives
clean:
	-del a.out core *.o *.obj *% *~ $(BIN)
